#!/bin/bash

    
SET_TAG="model-compare"
YOLOR_CFG="yolor_p6"
YOLOR_MODEL="yolor-p6-paper-541"
PROJECT_NAME="yolor-p6-paper-541_val"

cd ../val


# todo: gotta be a better way to automate this

# best speed
IMAGE_SIZE=512
BATCH_SIZE=24
for runs in {1..2}
do
	YOLOR_CFG=${YOLOR_CFG} YOLOR_MODEL=${YOLOR_MODEL} WANDB_TAGS=${SET_TAG} PROJECT_NAME=${PROJECT_NAME} IMAGE_SIZE=${IMAGE_SIZE} BATCH_SIZE=${BATCH_SIZE} ./run-val.sh
done


# Best mAP
IMAGE_SIZE=1280
BATCH_SIZE=1
for runs in {1..2}
do
	YOLOR_CFG=${YOLOR_CFG} YOLOR_MODEL=${YOLOR_MODEL} WANDB_TAGS=${SET_TAG} PROJECT_NAME=${PROJECT_NAME} IMAGE_SIZE=${IMAGE_SIZE} BATCH_SIZE=${BATCH_SIZE} ./run-val.sh
done


# 2nd best perf
IMAGE_SIZE=960
BATCH_SIZE=4
for runs in {1..2}
do
	YOLOR_CFG=${YOLOR_CFG} YOLOR_MODEL=${YOLOR_MODEL} WANDB_TAGS=${SET_TAG} PROJECT_NAME=${PROJECT_NAME} IMAGE_SIZE=${IMAGE_SIZE} BATCH_SIZE=${BATCH_SIZE} ./run-val.sh
done


# 3rd best perf
IMAGE_SIZE=768
BATCH_SIZE=8
for runs in {1..2}
do
	YOLOR_CFG=${YOLOR_CFG} YOLOR_MODEL=${YOLOR_MODEL} WANDB_TAGS=${SET_TAG} PROJECT_NAME=${PROJECT_NAME} IMAGE_SIZE=${IMAGE_SIZE} BATCH_SIZE=${BATCH_SIZE} ./run-val.sh
done

# 4th best perf
IMAGE_SIZE=640
BATCH_SIZE=12
for runs in {1..2}
do
	YOLOR_CFG=${YOLOR_CFG} YOLOR_MODEL=${YOLOR_MODEL} WANDB_TAGS=${SET_TAG} PROJECT_NAME=${PROJECT_NAME} IMAGE_SIZE=${IMAGE_SIZE} BATCH_SIZE=${BATCH_SIZE} ./run-val.sh
done
